const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()

const STORIES = {
  1: [
    { title: 'The Red Apple', content: 'I see a red apple.\nThe apple is big.\nI eat the apple.\nIt is good!', wordCount: 15 },
    { title: 'My Cat', content: 'I have a cat.\nMy cat is fat.\nMy cat can sit.\nI love my cat.', wordCount: 16 },
    { title: 'The Sun', content: 'The sun is up.\nThe sun is hot.\nI can see the sun.\nThe sun is big.', wordCount: 17 },
    { title: 'My Dog', content: 'I have a dog.\nMy dog is brown.\nMy dog can run fast.\nI love my dog.', wordCount: 16 },
    { title: 'The Ball', content: 'I have a red ball.\nThe ball is round.\nI can kick the ball.\nThe ball goes far.', wordCount: 17 },
    { title: 'The Big Tree', content: 'I see a big tree.\nThe tree is green.\nA bird sits in the tree.\nI like the tree.', wordCount: 18 },
    { title: 'My Room', content: 'This is my room.\nI have a bed.\nI have books and toys.\nI like my room.', wordCount: 16 },
    { title: 'The Fish', content: 'I have a fish.\nThe fish is orange.\nThe fish can swim.\nI like my fish.', wordCount: 15 },
    { title: 'I Can Move', content: 'I can run.\nI can jump.\nI can hop.\nI can spin.\nI love to move!', wordCount: 16 },
    { title: 'The Moon', content: 'The moon is up.\nThe moon is bright.\nI can see the moon.\nThe moon is my friend.', wordCount: 18 },
  ],
  2: [
    { title: 'The Little Dog', content: 'Tom has a little dog.\nThe dog likes to run.\nThe dog likes to jump.\nTom and the dog play all day.', wordCount: 22 },
    { title: 'A Rainy Day', content: 'Today it is raining.\nI wear my boots.\nI jump in the puddles.\nRain is so much fun!', wordCount: 20 },
    { title: 'My Family', content: 'I have a big family.\nMom, Dad, and my sister.\nWe eat dinner together.\nI love my family very much.', wordCount: 22 },
    { title: 'The Garden', content: 'Mom has a small garden.\nRed and yellow flowers grow there.\nWe water the flowers every day.\nBees come to visit the flowers.\nOur garden is beautiful.', wordCount: 29 },
    { title: 'My Best Friend', content: 'My best friend is Lily.\nWe go to school together.\nWe eat lunch together.\nWe play after school.\nLily is my good friend.', wordCount: 27 },
    { title: 'The Yellow Bus', content: 'I ride a yellow bus.\nThe bus takes me to school.\nI sit by the window.\nI see trees and houses.\nThe bus ride is fun!', wordCount: 30 },
    { title: 'My Lunch Box', content: 'I have a blue lunch box.\nMom puts an apple inside.\nShe puts a sandwich too.\nI eat it all at school.\nLunch is my favorite time.', wordCount: 31 },
    { title: 'The Playground', content: 'I love the playground.\nI can swing high.\nI can slide down.\nI run with my friends.\nThe playground is the best place!', wordCount: 27 },
    { title: 'My New Shoes', content: 'I got new red shoes today.\nThey are shiny and bright.\nI wore them to the park.\nI ran and jumped all day.\nI love my new shoes!', wordCount: 31 },
    { title: 'The Baby Bird', content: 'A baby bird is in the nest.\nIt calls for its mother.\nMom bird comes back with food.\nThe baby bird eats and smiles.\nSoon it will learn to fly.', wordCount: 32 },
  ],
  3: [
    { title: 'The Lost Bird', content: 'A little bird sat on a tree.\nSuddenly, the wind blew hard.\nThe bird fell from the branch.\n"Help!" said the bird.\nA kind girl heard the bird.\nShe picked it up and put it back.\nThe bird sang a happy song.', wordCount: 42 },
    { title: 'Baking Cookies', content: 'Mom and I made cookies today.\nWe mixed flour, eggs, and butter.\nWe put them in the oven.\nThe house smelled so sweet!\nWe shared the cookies with our neighbors.\nEveryone smiled and said thank you.', wordCount: 38 },
    { title: 'The Brave Mouse', content: 'Max was a small mouse.\nHe was afraid of the dark.\nOne night, the lights went out.\nMax took a deep breath.\n"I can do this," he said.\nHe walked through the dark room.\nWhen the lights came back, Max felt proud.', wordCount: 46 },
    { title: 'The Rainbow', content: 'After the rain, Mia looked up.\nShe saw a big rainbow in the sky.\nRed, orange, yellow, green, blue — so many colors!\n"Wow!" she said to her brother.\nThey ran outside to look at it.\nThe rainbow made them feel happy.\nNature is so beautiful.', wordCount: 48 },
    { title: "Grandma's Garden", content: 'Lily visited grandma on Saturday.\nGrandma had a big garden full of vegetables.\nThey picked tomatoes and cucumbers together.\n"Try one," said Grandma.\nLily bit into a tomato. It was sweet!\n"Can I plant my own seeds?" Lily asked.\n"Of course," Grandma smiled.', wordCount: 46 },
    { title: 'The Snowman', content: 'Jake woke up to see snow outside.\nHe put on his coat and ran out.\nHe rolled three big snowballs.\nHe stacked them up carefully.\nHe gave the snowman a carrot nose and a scarf.\n"Hello, friend!" Jake said.\nThe snowman seemed to smile back.', wordCount: 48 },
    { title: 'The New Puppy', content: 'Anna got a puppy on her birthday.\nThe puppy had soft brown fur.\nAt first, the puppy was shy.\nIt hid under Anna\'s bed.\nAnna sat quietly and waited.\nSlowly, the puppy came out.\nIt licked her hand.\n"I\'ll call you Coco," Anna said.', wordCount: 48 },
    { title: 'The Helping Hand', content: 'On the way home, Sam saw an old man.\nThe man was carrying heavy bags.\nSam ran over to help.\n"May I carry those for you?" Sam asked.\nThe old man smiled warmly.\nTogether they walked to his house.\n"Thank you, young man," the old man said.', wordCount: 48 },
    { title: 'Playing in the Rain', content: 'It rained all afternoon.\nLeo and his sister stayed inside.\nThey built a fort with blankets.\nThey read books and told stories.\nWhen the rain stopped, a rainbow appeared.\nThey ran outside to see it.\nRainy days could be wonderful too.', wordCount: 40 },
    { title: 'The Little Kite', content: 'Ben got a new kite for his birthday.\nIt was red with a long blue tail.\nDad took him to the park.\nThe wind picked up the kite quickly.\nBen held the string tight and laughed.\nThe kite danced high above the trees.\n"Let\'s come back tomorrow!" Ben cried.', wordCount: 51 },
  ],
  4: [
    { title: 'The Missing Toy', content: 'Tom could not find his toy car anywhere.\nHe looked under his bed.\nHe looked in the toy box.\nHe looked behind the sofa.\nIt was not there!\nTom sat on the floor and thought.\nThen he remembered — yesterday he left it in the garden!\nHe ran outside.\nThere it was, in the grass.\nTom smiled and picked it up.\n"I will put it away properly next time," he said.', wordCount: 75 },
    { title: 'A Day at the Farm', content: "Mia's class went to a farm.\nThey saw cows, pigs, and chickens.\nA farmer showed them how to milk a cow.\nThe milk was warm and fresh.\nThey fed carrots to the horses.\nMia held a baby chick in her hands.\nIt felt soft and warm.\nAt the end of the day, the farmer gave each child a small jar of honey.\nMia thought it was the best trip ever.", wordCount: 74 },
    { title: 'The Friendly Dragon', content: 'Everyone in the village was afraid of the dragon.\nBut the dragon was not mean.\nHe was just lonely.\nOne day, a little girl named Rosa walked up the mountain.\n"Hello, Dragon," she said.\n"Hello," the dragon said softly.\nThey sat and talked all afternoon.\nThe dragon told funny stories.\nRosa laughed and laughed.\nSoon the whole village came to meet the dragon.\nNow he had many friends.', wordCount: 73 },
    { title: 'The Big Storm', content: 'Dark clouds gathered over the town.\nWind blew the leaves off the trees.\nRain fell hard on the windows.\nLily and her dad sat by the fireplace.\nDad told stories while thunder rumbled outside.\nThen the lights went out.\nThey lit candles and made hot chocolate.\nThe storm outside made the house feel warm and cozy inside.\nWhen morning came, the sky was clear and bright.\nLily decided she liked storms after all.', wordCount: 76 },
    { title: "Sam's Birthday", content: "Today was Sam's seventh birthday.\nHe woke up early with a big smile.\nDownstairs, balloons filled the living room.\nHis family sang happy birthday.\nMom made a chocolate cake.\nFriends came over to play.\nThey played games in the yard.\nAt cake time, Sam made a wish.\nHe blew out all seven candles in one breath!\nEveryone cheered.\nSam got books, toys, and a shiny new bike.\nIt was the best birthday yet.", wordCount: 77 },
    { title: 'The Old Bridge', content: 'There was an old stone bridge over the river.\nThe children loved to sit on it.\nThey watched fish swim below.\nOne autumn day, the bridge cracked.\nThe village people were worried.\nA young engineer came to fix it.\nShe worked hard for two weeks.\nFinally, the bridge was strong again.\nThe whole village celebrated.\nThe children were the first to run across it.\nThe old bridge stood for many more years.', wordCount: 73 },
    { title: 'The Sick Kitten', content: 'One morning, Jake found a tiny kitten by the gate.\nThe kitten was wet and shivering.\nJake picked it up and brought it inside.\nHe dried it with a towel.\nHe gave it warm milk.\nThe kitten was too sick to eat much.\nMom called the vet.\nThe vet said the kitten needed rest and care.\nJake looked after it every day.\nAfter one week, the kitten was jumping and playing.\nJake named it Lucky.', wordCount: 76 },
    { title: 'Making Friends', content: 'Maya moved to a new town in September.\nEverything felt strange and new.\nShe did not know anyone at school.\nAt lunch, she sat alone.\nThen a girl named Zoe sat across from her.\n"Hi, I\'m Zoe. Is this seat free?"\nMaya smiled and nodded.\nThey talked about books and animals.\nZoe loved dogs. Maya loved cats.\nThey laughed about it.\nBy the end of the day, they had exchanged numbers.\nMoving towns was not so bad after all.', wordCount: 80 },
    { title: 'The Little Seed', content: 'In the spring, Ben planted a tiny seed.\nHe watered it every morning.\nHe made sure it got sunlight.\nFor two weeks, nothing happened.\nBen was losing hope.\nThen one day, a tiny green shoot appeared!\nHe called his mom to come and look.\n"You did it!" she said proudly.\nBen kept caring for his plant.\nBy summer, it had grown tall with bright yellow flowers.\nAll his patience had paid off.', wordCount: 74 },
    { title: 'A Walk in the Park', content: "On Sunday, Lily and her grandpa walked in the park.\nThey saw ducks on the pond.\nGrandpa brought bread to feed them.\nThe ducks waddled over quickly.\nLily laughed at how funny they moved.\nThey sat on a bench and ate ice cream.\nGrandpa told Lily about when he was young.\nHe used to catch frogs in that very pond.\n\"Can we catch frogs too?\" Lily asked.\n\"Maybe next time,\" Grandpa smiled.", wordCount: 74 },
  ],
  5: [
    { title: 'The Magic Paintbrush', content: "Leo found an old paintbrush in his grandfather's shed.\nIt looked ordinary — wooden handle, soft bristles.\nBut when Leo painted the sun, it felt warmer in the room.\nWhen he painted rain clouds, the window misted up.\nHe ran to tell his mother.\n\"Grandpa always said imagination was magic,\" she smiled.\nLeo sat down and painted a big garden full of flowers.\nHe painted butterflies and a pond with golden fish.\nHe painted a boy in the garden — himself — running barefoot through the grass.\nLooking at his painting, Leo felt something he hadn't felt in a long time: joy.\nMaybe the magic was not in the brush.\nMaybe it had been inside him all along.", wordCount: 120 },
    { title: 'A Letter to Grandpa', content: "Emma hadn't seen her grandpa for six months.\nHe lived far away, in a small house by the sea.\nOne evening, Emma decided to write him a letter.\nShe told him about her new school.\nShe told him about her hamster, Peanut.\nShe drew a picture of Peanut at the bottom of the page.\nThree weeks later, a letter arrived in a yellow envelope.\nGrandpa wrote back about the seagulls outside his window.\nHe said they were very noisy but he loved them.\nHe drew a picture of a seagull for Emma.\nBelow the drawing he wrote: \"Missing you every day.\"\nEmma folded the letter and kept it under her pillow.\nShe started writing back right away.", wordCount: 124 },
    { title: 'Snow Day', content: "School was cancelled because of the snow.\nMia and her brother Jake ran outside before breakfast.\nThe world was white and silent.\nThey built a snowman in the front yard.\nHe got a red scarf and two black buttons for eyes.\nThen they had a snowball fight.\nJake was a better thrower, but Mia was faster.\nShe dodged every single one of his snowballs.\nBy noon, their fingers were frozen.\nMom called them in for hot soup and toast.\nThey sat by the heater, still laughing.\nThat evening, the news said school would also be cancelled tomorrow.\nJake and Mia looked at each other and cheered.", wordCount: 116 },
    { title: 'First Day at School', content: "The night before school started, Lily couldn't sleep.\nShe stared at the ceiling and worried.\nWhat if no one wanted to be her friend?\nWhat if the teacher was strict?\nIn the morning, Mom braided her hair and made her favorite pancakes.\n\"You'll be great,\" Mom said.\nAt school, Lily found her name on a desk by the window.\nA girl with curly hair sat next to her.\n\"I'm Clara,\" she said. \"I'm nervous too.\"\nThat made Lily feel better right away.\nDuring art class, they painted together.\nBy lunchtime, they were already sharing jokes.\nWalking home, Lily thought: maybe the best things in life start with a little fear.", wordCount: 120 },
    { title: 'The Treasure Map', content: "On a rainy Saturday, Tom found a folded piece of paper in his grandfather's old book.\nHe unfolded it carefully.\nIt was a map — hand-drawn, with dotted lines and small pictures of trees, rocks, and a big X.\nTom's heart jumped.\nHe called his sister Ana.\nTogether they grabbed raincoats and followed the map through the backyard.\nPast the apple tree. Past the old fence. Behind the big rock.\nThey dug with sticks.\nThree inches down, they hit something metal.\nIt was a tin box.\nInside was a note that said: \"For whoever is brave enough to find this.\"\nBelow the note was a bag of old coins and a chocolate bar.\nThe chocolate was stale, but they ate it anyway, laughing in the rain.", wordCount: 135 },
    { title: 'The Lost Puppy', content: "On her way home, Chloe found a small dog sitting by a trash can.\nHe was shaking and his fur was dirty.\nThere was no collar and no owner in sight.\nChloe knelt down. The dog crawled into her arms.\n\"You must be lost,\" she said softly.\nShe brought him home.\nMom helped clean him up and find some food.\nDad said they should post photos in the neighborhood.\nFor three days, no one called.\nThe dog slept at the foot of Chloe's bed.\nOn the fourth day, a little boy knocked on their door.\nHis eyes were red. He'd been crying for days.\n\"That's Max,\" the boy whispered.\nChloe felt sad to let him go.\nBut watching the boy hug Max tight, she knew it was right.", wordCount: 137 },
    { title: 'The Perfect Gift', content: "Mom's birthday was in three days and Nora had no money.\nShe emptied her piggy bank — just sixty cents.\nShe asked her brother for ideas.\n\"You could make something,\" he said.\nNora thought hard.\nShe remembered Mom always said her handwriting was beautiful.\nNora sat down and wrote Mom a long letter — about all her favorite memories together.\nThe picnic in the rain. The night they read a whole book in one sitting. The day Mom stayed up to help with the science project.\nShe folded the letter into the shape of a heart.\nOn Mom's birthday, she gave it with a hug.\nMom read it slowly.\nWhen she looked up, there were tears on her cheeks.\n\"This is the best gift I've ever received,\" she said.", wordCount: 133 },
    { title: 'A Helping Paw', content: "Every morning, Mrs. Chen walked her old dog, Biscuit, around the park.\nBiscuit was twelve years old and moved slowly now.\nOne morning, Biscuit stopped and wouldn't move.\nMrs. Chen worried.\nA teenage boy named Felix happened to walk by.\nHe noticed the old dog and stopped.\n\"Is he okay?\"\n\"He's just old,\" Mrs. Chen said sadly. \"Some mornings are harder.\"\nFelix knelt down and gently stroked Biscuit's ears.\nThe old dog's tail began to wag — slowly at first, then faster.\nBiscuit stood up and took a few steps.\n\"He likes you,\" Mrs. Chen said with surprise.\nFrom that day on, Felix stopped by every morning before school.\nBiscuit always waited for him at the garden gate.\nSometimes the smallest kindness makes the biggest difference.", wordCount: 131 },
    { title: 'The Singing Stone', content: "High in the mountains, there was a stone that hummed.\nNot loudly — just a low, soft sound, like the hum of a lullaby.\nPeople in the village said it had been there for hundreds of years.\nA scientist came to study it.\nShe brought equipment and spent three days taking readings.\nAll her machines showed nothing unusual.\nOn the last evening, she sat beside the stone alone.\nThe mountains were quiet. The sun was setting.\nThen she heard it — so soft she thought she imagined it.\nShe stayed perfectly still and listened.\nIt felt like the stone was breathing.\nShe wrote in her notebook: \"No scientific explanation. But it's real.\"\nShe never published that page.\nBut she came back every year, just to listen.", wordCount: 126 },
    { title: 'The Night Sky', content: "The power went out across the whole town.\nFor the first time in years, the street lights were dark.\nFamilies stepped outside, unsure what to do.\nThen someone looked up.\n\"Stars!\" a young girl called out.\nWithout the city lights, the sky was full of them.\nHundreds, then thousands. More than anyone had seen before.\nNeighbors who barely knew each other stood together on the street.\nAn old man named George brought out a telescope.\nHe had owned it for forty years but rarely used it.\nHe showed the children Saturn's rings and the craters of the moon.\nA little boy asked, \"Are there people up there?\"\nGeorge smiled. \"That's the right question to ask.\"\nThe power came back at midnight.\nBut nobody went inside right away.", wordCount: 132 },
  ],
  6: [
    { title: 'Two Best Friends', content: "Maya and Jess had been best friends since kindergarten.\nThey did everything together — walked to school, shared lunch, and called each other every night.\nBut this year, they were in different classes for the first time.\nJess was put in Mrs. Brown's class. Maya was in Mr. Lee's class.\nAt first, it didn't feel like a big deal.\nBut as weeks passed, Jess started spending more time with her new classmates.\nMaya ate lunch alone twice.\nShe felt something tighten in her chest.\nOne day, she finally said something.\n\"Do you even want to be friends anymore?\"\nJess looked surprised. \"Of course I do. Why would you think that?\"\nMaya explained how she'd been feeling.\nJess listened quietly.\n\"I didn't know,\" she said. \"I'm sorry.\"\nThat evening they took a long walk like they used to.\nThey talked and laughed and shared a bag of chips.\nFriendship, they decided, was something you had to choose every day.\nNot just when it was easy.", wordCount: 162 },
    { title: 'The Kite Festival', content: "Every spring, the town held a kite festival in the meadow by the river.\nThousands of kites of every shape and color filled the sky.\nThis year, eleven-year-old Sam had built his own kite for the first time.\nHe'd worked on it for a month — cutting bamboo, stretching fabric, painting a dragon on the front.\nHis older sister Jade helped him tie the strings properly.\nWhen the day came, Sam was nervous.\nHe ran across the field and let the string out slowly.\nThe kite wobbled — then climbed. Higher and higher it went.\nPeople around him pointed and smiled at the dragon kite.\nA gust of wind suddenly caught it and pulled hard.\nSam held on with both hands.\n\"Let it breathe,\" said an old man beside him. \"Don't fight the wind. Work with it.\"\nSam relaxed his grip.\nThe kite steadied and soared beautifully.\nHe didn't win any prize that day.\nBut he felt prouder than he ever had.", wordCount: 166 },
    { title: 'A Surprise for Mom', content: "Three weeks before Mother's Day, Lily and her brother Kai made a plan.\nThey would cook Mom a full breakfast — eggs, toast, orange juice, and her favorite blueberry muffins.\nBut they had a problem: neither of them knew how to cook.\nKai found a simple recipe online.\nLily wrote a shopping list.\nThey saved their pocket money and walked to the corner store.\nThe night before, they set their alarms for seven.\nIn the morning, they crept downstairs while Mom slept.\nThe first batch of muffins was burned.\nThey opened the windows and started again.\nThe second batch looked better.\nKai scrambled eggs while Lily squeezed the oranges.\nThere was flour on the ceiling and juice on the floor.\nBut by eight-thirty, a full breakfast sat on the table.\nMom came downstairs and stopped.\nShe looked at the messy kitchen and then at her two children, flour on their faces, grinning.\n\"Happy Mother's Day,\" said Lily.\nMom didn't say anything for a moment.\nThen she pulled them both close.", wordCount: 175 },
    { title: 'The Old Tree House', content: "The tree house had been in the oak tree since before any of the kids were born.\nNobody was sure who built it.\nThe wood was old and some of the planks were soft.\nParents warned their children to stay away.\nBut twelve-year-old Dan couldn't help himself.\nOne afternoon, he climbed up carefully, testing each board before stepping.\nThe inside was small but dry.\nThere were old comic books in a plastic bag.\nA tin cup. A handwritten list of names and years going back to 1987.\nDan ran his finger down the list.\nAt the bottom, in faded pencil, was a name he recognized: his father's name, followed by 1991.\nHis dad had never mentioned this place.\nThat evening, Dan showed him the list.\nHis dad went quiet for a moment.\nThen he smiled — a different kind of smile, one Dan had never seen before.\n\"I haven't thought about that place in twenty years,\" he said.\n\"Will you come up and see it?\" Dan asked.\nHis dad looked at the tree for a long time.\n\"Yes,\" he finally said. \"I think I will.\"", wordCount: 185 },
    { title: 'The Science Project', content: "The science fair was in two weeks and Priya hadn't started her project yet.\nEvery other idea felt boring or too hard.\nHer partner, Marcus, was getting frustrated.\n\"We need to pick something,\" he said. \"Today.\"\nPriya looked around the kitchen for inspiration.\nShe noticed the plants on the windowsill leaning toward the glass.\n\"What if we test whether plants grow toward light faster with different colors of light?\"\nMarcus thought about it.\n\"Okay. That's actually interesting.\"\nThey bought three identical plants and set them up — one in full light, one in dim light, one with a colored filter over the window.\nEvery day, they measured and photographed.\nAt the fair, their presentation was one of the few with real data.\nThey didn't win first place.\nBut the judge, a university professor, asked them extra questions for ten minutes.\n\"That,\" said Priya on the way home, \"felt better than winning.\"", wordCount: 162 },
    { title: 'Storm on the Mountain', content: "The hike was supposed to take four hours.\nNine-year-old Finn and his father started early, when the sky was clear blue.\nThey were halfway up when the clouds came in fast.\nThe temperature dropped. Dad checked his phone — no signal.\n\"We should turn back,\" Dad said.\nFinn wanted to argue. They were so close to the top.\nBut the wind was picking up now and the path was getting wet.\n\"Okay,\" he said quietly.\nThey moved fast down the trail.\nThe rain started before they reached the forest.\nThunder rolled across the valley.\nFinn stayed close to his dad, stepping where he stepped.\nWhen they reached the car, they were both soaked through.\nDad turned on the heater and handed Finn a granola bar.\n\"Good call today,\" Dad said.\n\"Turning back?\"\n\"Knowing when to turn back. Not everyone does.\"\nFinn ate his granola bar and watched the storm move across the mountain above them.\nThe summit could wait.", wordCount: 165 },
    { title: 'The Talking Parrot', content: "Uncle Phil's parrot, Captain, had a vocabulary of over two hundred words.\nWhen twelve-year-old Zara came to stay for the summer, she was fascinated.\nEvery morning she sat beside Captain's cage with a notebook.\nAt first his words seemed random — \"Pretty bird!\" and \"Where's my cracker?\" and \"Phil! Phil!\"\nBut after a week, Zara noticed patterns.\nCaptain always said \"Storm coming\" before rain.\nHe said \"Someone's here\" about thirty seconds before a visitor knocked.\nAnd every evening at exactly five-thirty, he said \"Time to go home\" in a very sad voice.\n\"What does that mean?\" Zara asked Uncle Phil.\nUncle Phil went quiet.\n\"Captain belonged to my wife before she passed,\" he said. \"Five-thirty was when she used to finish work and come home.\"\nZara closed her notebook.\nThat evening at five-thirty, she sat next to Captain's cage.\nShe didn't say anything. Neither did he.\nBut they both stayed there until six.", wordCount: 170 },
    { title: 'The Lost Library Book', content: "The library book was due on Friday.\nOn Thursday evening, Mia couldn't find it anywhere.\nShe searched her room, her bag, under the sofa, behind the bookshelf. Nothing.\nShe told her mom, who told her to retrace her steps.\nMia thought hard.\nShe'd read it at the park — on the bench by the fountain.\nIt was dark and the park was closed.\nMia barely slept.\nIn the morning, she walked to the park the moment it opened.\nThe bench was empty. Her heart sank.\nThen she saw the groundskeeper near the gate.\n\"Excuse me — did you find a library book?\"\nHe went into his small office and came back with a familiar blue cover.\n\"Found it yesterday. Figured someone would come looking.\"\nMia held it to her chest.\n\"Thank you so much.\"\nShe returned it to the library that afternoon — one day late.\nThe librarian charged her twenty cents.\nMia paid and didn't complain.\nIt felt like the best twenty cents she'd ever spent.", wordCount: 168 },
    { title: "The River's Secret", content: "For as long as anyone could remember, the old river at the edge of town ran clean and clear.\nYou could see the smooth stones at the bottom.\nFish darted between the reeds. Kids swam there every summer.\nBut this July, something was wrong.\nThe water was darker. The fish were gone.\nElla, who was thirteen, noticed first.\nShe walked upstream for three miles until she found it: a pipe draining gray water from an old factory into the river.\nShe photographed it and wrote a report.\nShe brought it to her science teacher, who helped her contact the local council.\nThree weeks later, the factory was inspected and fined.\nBy September, the water was running clear again.\nSmall fish returned by October.\nElla's teacher nominated her for a regional award.\nElla didn't care much about the award.\nShe just went back to the river on the last warm day of autumn and sat with her feet in the water.\nThat was enough.", wordCount: 163 },
    { title: 'The Night Fisherman', content: "Old Thomas had fished the lake at night for thirty years.\nHe knew every corner of it in the dark — where the water was shallow, where the big fish rested, where the current curved around the eastern bank.\nHis grandson Eddie had never been along before.\nThis summer, Thomas asked him.\nEddie expected it to be boring.\nThey sat in the boat for an hour without a word.\nEddie grew restless.\nThen Thomas said quietly, \"Listen.\"\nEddie listened.\nThe water lapping the hull. A frog near the reeds. Wind in the rushes.\nSlowly, his restlessness faded.\n\"I don't know how to be quiet,\" Eddie admitted.\n\"Nobody does, at first,\" said Thomas.\nThey caught two fish and threw them back.\nOn the way home, the sky was turning pale pink.\nEddie realized he hadn't thought about his phone once all night.\n\"Same time next week?\" Thomas asked.\nEddie nodded. \"Same time next week.\"", wordCount: 162 },
  ],
  7: [
    { title: 'The Last Day of Summer', content: "The last day of summer was always the same in the Chen household — a long, slow breakfast, then a drive to the lake one final time before school began.\nThis year was different. This year, Sophie was starting middle school, and everything felt heavier than it used to.\nAt the lake, she sat on the dock and dangled her feet in the water while her younger brother ran circles on the grass.\nHer dad sat beside her.\n\"Nervous?\" he asked.\n\"A little,\" she said. \"What if I'm not good enough?\"\nHer dad was quiet for a moment.\n\"You know what I remember about the first day of every new thing in my life? I remember being sure I wasn't ready. And then doing it anyway.\"\n\"Did it get easier?\"\n\"Sometimes. But even when it didn't, I was always glad I went.\"\nSophie watched a dragonfly skim across the water.\n\"What if the friends I make aren't like my old friends?\"\n\"They won't be. They'll be different. Some better, some worse. But new.\"\nSophie picked up a flat stone and skipped it across the lake. It bounced six times.\nHer brother cheered from the shore.\n\"Six,\" said her dad. \"Your record.\"\nSomething in her chest had loosened.\nOn the drive home, she watched the fields go by and decided she was ready.", wordCount: 210 },
    { title: "The Cartographer's Daughter", content: "Mia's father made maps for a living.\nNot digital maps — real ones, drawn by hand on thick paper with careful lines and tiny script.\nHe mapped hiking trails, coastal paths, neighborhoods that were changing too quickly to be captured by satellites.\nAs a child, Mia had thought this was the most ordinary thing in the world.\nBut when her geography teacher held up one of his maps during class, Mia felt something she hadn't expected: pride.\nAfter school that day, she went to her father's studio and watched him working — a small brush, a pot of ink, the scratch of his pen filling in the name of a lane she recognized.\nHe worked slowly, correcting himself, erasing, starting again.\n\"Why don't you just use a computer?\" she asked.\n\"I do, sometimes,\" he said. \"But there's something a handmade map has that a digital one doesn't.\"\n\"What?\"\nHe pointed to a small inked mistake near the edge of a trail.\n\"The person. The map remembers who made it.\"\nMia thought about that on the walk home.\nShe found an old notebook and began drawing her own neighborhood from memory — every alley she knew, every shortcut, every house with a good tree.\nShe was still at it when her father called her for dinner.\n\"You started a map,\" he said when he saw it.\n\"I'm trying.\"\nHe nodded once, seriously, the way he did when something mattered.\n\"Take your time. Good maps aren't rushed.\"", wordCount: 228 },
    { title: 'The Broken Radio', content: "The old radio on the kitchen shelf had stopped working three years ago.\nIt sat there because nobody got around to throwing it out.\nThis summer, Eli decided to fix it.\nHe was fourteen and had never fixed anything more complicated than a bicycle tire, but there were videos for this sort of thing.\nHe watched seventeen of them.\nHe took the radio apart on the kitchen table, parts spread carefully on a tea towel.\nHis mother watched from the doorway.\n\"You'll break it worse,\" she said.\n\"It's already broken,\" he pointed out.\nShe didn't argue with that.\nFor three weeks, he replaced parts he ordered online, one at a time.\nThere were setbacks. He resoldered the same connection four times.\nThe dial knob cracked when he reassembled it. He glued it together and painted over the crack with a tiny brush.\nOn the twenty-third day, he plugged it in.\nStatic at first. Then, slowly, a voice.\nA music station from the city.\nHis mother came in at the sound.\nFor a moment she just stood there.\n\"That's the station your grandmother used to listen to,\" she said quietly.\nEli didn't know that.\nHe adjusted the dial until the signal was clear.\nThey listened to the whole song together before either of them spoke again.", wordCount: 215 },
    { title: 'Paper Boats', content: "Every time it rained heavily, the gutter in front of the old house filled up and moved fast like a river.\nWhen Maya was small, her grandfather had taught her to make paper boats.\nThey would stand at the edge of the gutter and launch them, watching them sail past the neighbor's gate, around the corner, and out of sight.\n\"Where do they go?\" Maya always asked.\n\"On to the ocean,\" her grandfather always said.\nShe knew that couldn't be true — the gutter ran to a drain three houses down.\nBut she liked the answer anyway.\nNow she was twelve and her grandfather had died in January.\nIt was the first heavy rain since then.\nMaya stood at the window for a long time, watching the gutter fill.\nShe went to find paper.\nShe folded a boat — the same way he had shown her, though it took three tries before she remembered the final fold.\nShe walked outside barefoot. The rain was warm.\nShe bent down and placed the boat in the current.\nIt wobbled, then steadied, then moved.\nShe watched it until it was gone around the corner.\n\"On to the ocean,\" she said out loud, in her grandfather's voice.\nThe rain kept falling.\nMaya stayed outside for a while, not minding it at all.", wordCount: 218 },
    { title: "The Beekeeper's Secret", content: "Nora had walked past the old beekeeper's house hundreds of times without stopping.\nThe hives were stacked at the back of the garden, barely visible through the hedge.\nSometimes in summer she heard the low hum from the sidewalk.\nOne afternoon her bicycle got a flat tire right outside his gate.\nThe old man — Mr. Adler — came out with a pump.\n\"Sit down while I fix that,\" he said.\nNora sat on the garden wall, watching him work.\nHe was in his seventies, with large steady hands and a very calm way of moving.\n\"Do you keep many hives?\" she asked.\n\"Twelve,\" he said. \"Used to be thirty, when I was younger.\"\nHe looked at the hives when he said this.\n\"Aren't you afraid of the stings?\"\n\"I was, in the beginning. Then I learned that fear is mostly just unfamiliarity. You get stung a few times and you stop imagining it as worse than it is.\"\nHe handed her the bicycle.\nNora hesitated.\n\"Could I watch you work with them sometime?\"\nMr. Adler studied her for a moment.\n\"Saturday morning,\" he said. \"Eight o'clock. Wear long sleeves.\"\nNora rode home faster than usual.\nShe wasn't sure she was brave enough.\nBut she was going to try.", wordCount: 213 },
    { title: 'The Wrong Door', content: "The music room and the science lab were at opposite ends of the same corridor.\nOn his first week at the new school, eleven-year-old James turned right when he should have turned left.\nHe pushed open a door and found himself in a dim room full of instruments.\nA girl was sitting at the piano, playing something slowly.\nShe stopped when she saw him.\n\"Music is on Tuesdays,\" she said. \"Today is Thursday.\"\n\"I'm lost,\" he said honestly.\nShe pointed him back into the corridor and told him to count three doors down.\nOn Tuesday, James had music.\nHe sat at the back, since he'd played guitar for four years and wasn't sure what the class would cover.\nThe same girl was at the piano.\nThe teacher asked for volunteers.\nJames didn't raise his hand, but the girl pointed at him.\n\"He has the posture of someone who plays.\"\nThe teacher asked him to come forward.\nJames played the first eight bars of a piece he'd been working on at home — clean and careful.\nThe class was quiet for a moment.\n\"Good,\" said the teacher simply.\nThe girl at the piano didn't say anything.\nBut at the end of class she said, \"You can play here on Thursdays if you want. I'll be there anyway.\"\nJames considered it.\n\"Okay,\" he said.\nIt was the best thing that had happened since he changed schools.", wordCount: 228 },
    { title: 'One Hundred Days', content: "The doctor told Sam's mother that Sam would need to stay in the hospital for at least one hundred days.\nSam was nine.\nHe counted on his fingers the first time he heard this. A hundred days was more than three months.\nHis room had a window that looked out on the hospital car park.\nBeyond the car park was a narrow strip of sky.\nSam decided he would make the most of that strip of sky.\nHe started drawing the clouds every day.\nNot the same clouds — every day they were different.\nHe drew them in a small notebook his aunt brought him.\nTall clouds. Flat clouds. Clouds that looked like animals or countries or spilled milk.\nSome days the sky was completely clear and he drew an empty page.\nHe labeled each page with the day number.\nBy day forty, the nurses had started stopping by to see what he'd drawn.\nBy day seventy, the doctor brought his young daughter to look at the notebook.\nShe pointed at a cloud on day fifty-three. \"That one looks like a rabbit.\"\nSam had thought it looked like a submarine, but he didn't say that.\nOn day one hundred, they let him go home.\nHe took the notebook with him.\nThat evening, he sat in the garden and looked at the sky for a long time.\nThen he drew one more page and labeled it: Day 101.", wordCount: 232 },
    { title: 'The Long Way Round', content: "Noah took the long way home.\nMost kids cut through the parking lot behind the supermarket, which saved seven minutes.\nNoah went the long way — around the park, across the footbridge, down the lane behind the old houses.\nHis mother had pointed out the footbridge to him when he was five.\n\"That's where your great-grandfather used to fish,\" she said.\nHe didn't know why that made the bridge special.\nHis great-grandfather had died before Noah was born.\nBut he had gone the long way every day since then, and now it was just habit.\nOn the footbridge, he always stopped and leaned over the railing.\nSometimes there were fish in the water below. Sometimes just the dark reflection of the sky.\nHe had seen a heron there once, standing perfectly still in the shallows, like a statue.\nHe had never told anyone about the heron in case it was never there again.\nOne afternoon in November, his friend Jay asked why he always came from that direction.\n\"I like that bridge,\" Noah said finally.\n\"What's special about it?\"\nNoah looked back toward the park.\n\"Nothing,\" he said. \"That's sort of the point.\"\nJay didn't understand. But he walked with Noah the long way anyway.\nWhen they crossed the bridge, Noah looked over the railing.\nThere was the heron.\nNoah didn't say anything.\nSome things were better kept to yourself.", wordCount: 228 },
    { title: 'Three Hours in the Dark', content: "The power cut happened at six in the evening, in the middle of autumn.\nSophia's family sat in the kitchen, unsure what to do.\nEveryone reached for their phones at the same time.\nHalf had dead batteries.\nMom found candles in the cupboard under the sink.\nThey lit four of them and placed them around the kitchen table.\nIt took a moment before anyone spoke.\n\"Now what?\" said her brother Leo.\nDad suggested cards. Nobody was enthusiastic.\nBut then Leo said, \"Let's do that game where you have to tell something true that nobody knows.\"\nThey played for two hours.\nSophia learned that her mother had once wanted to be a marine biologist. That her father had a fear of deep water. That Leo, who was seventeen, had been keeping a journal since he was twelve.\nIn return, Sophia told them that she'd been having trouble sleeping for three months and hadn't wanted to say anything.\nHer mother reached across the table and held her hand.\nNo one said much after that.\nBut something had changed in the kitchen.\nWhen the lights came back on, it felt almost too bright.\nLeo blew out the candles slowly, one by one.\n\"Same time next week?\" he said.\nEveryone laughed.\nBut Sophia noticed that nobody reached for their phones right away.", wordCount: 218 },
    { title: 'The Waiting Room', content: "The hospital waiting room had thirty-two chairs arranged in four rows.\nTen-year-old Lily counted them twice.\nShe was good at noticing things when she was trying not to think.\nHer grandmother was in surgery. It had been three hours.\nHer father paced. Her mother read the same two pages of a magazine over and over.\nLily watched the other people in the room.\nA man in paint-covered overalls who kept checking the door. An old woman who slept sitting upright, her handbag balanced on her lap. A teenage boy who played games on his phone without making a sound.\nAll these strangers, Lily thought, waiting for someone they loved.\nThat idea made the room feel different — less lonely and more full.\nShe got up and walked to the vending machine.\nWith her own money she bought a small packet of cookies.\nShe brought them to the teenager without a word and held them out.\nHe looked up, surprised. Then he took the packet and said, \"Thanks.\"\nLily went back to her seat.\nHalf an hour later, her father's name was called.\nThe surgeon came out smiling.\n\"She's out. It went well.\"\nLily let out a breath she felt like she'd been holding for three hours.", wordCount: 205 },
  ],
  8: [
    { title: 'The Last Shelf', content: "The bookshop had been on the corner of Elm and Fifth for forty-three years.\nMrs. Hartley had run it alone for the last twelve, since her husband died.\nEvery week the town had a little less of what it used to be — the hardware store gone, the bakery gone, the cinema gone — until the bookshop was one of the last old things left.\nMrs. Hartley was considering closing.\nShe hadn't told anyone.\nBut a thirteen-year-old named Celia, who came in every Saturday and read for two hours without buying anything, had noticed.\nThe boxes stacked near the back wall. The reduced hours sign in the window.\n\"Are you closing?\" Celia asked one Saturday.\nMrs. Hartley looked at her over her reading glasses.\n\"I'm thinking about it. It's a lot of work for not much money.\"\n\"What would happen to the books?\"\n\"Some to libraries. Some to charity. Some I'd keep.\"\nCelia was quiet for a while.\nThen she said, \"What if I helped? On Saturdays. For free.\"\n\"You're thirteen.\"\n\"I know how to file things. I'm good at recommending. Mrs. Park next door bought three books last week because I told her about them.\"\nThat was true. Mrs. Hartley had seen it happen.\n\"I can't pay you.\"\n\"I know.\"\nMrs. Hartley looked at the girl for a long time.\n\"All right,\" she said. \"Saturday mornings. Eight to noon.\"\nCelia came the following Saturday with a notebook.\nIn the first hour she reorganized the poetry section by feel — putting the ones she thought should be beside each other, beside each other.\nMrs. Hartley watched from the back.\nShe didn't close the shop that year.\nOr the year after.", wordCount: 268 },
    { title: 'Navigation', content: "The summer my grandfather taught me to navigate by stars was the summer everything else in my life felt uncertain.\nI was twelve, and my parents were separating — not loudly, not with arguments I could point to, but with the slow, quiet withdrawal of two people deciding they were better apart.\nGrandfather noticed something was wrong the second day I arrived at his house.\nHe didn't ask directly. He never did.\nInstead, on the third night, he came to my room at eleven and said, \"Get dressed. Bring a jacket.\"\nWe drove to the top of the hill behind his property.\nHe had a star chart and a red flashlight that wouldn't ruin your night vision.\nFor two hours, he taught me how to find north using Polaris, how the constellations moved through the sky, how sailors used to cross oceans using only what they could see above them.\n\"What if it was cloudy?\" I asked.\n\"Then you waited. Or you used what you knew of the wind and the water and made your best guess.\"\n\"What if your best guess was wrong?\"\n\"Then you corrected course.\"\nI thought about that. He didn't say anything else, and neither did I.\nBut I understood that he wasn't only talking about stars.\nWe stayed until the sky began to lighten.\nOn the drive home he let me hold the star chart.\nI kept it for years — folded in the back of a drawer — until I needed to look at it again.\nYou always need to look at it again.", wordCount: 252 },
    { title: 'The Interview', content: "The summer before eighth grade, Zara's school announced a program: every student would interview an elderly person in their community and write up what they learned.\nZara chose her neighbor, Mr. Okafor, who was eighty-one and had lived in the same house for fifty years.\nShe came with a notebook and a list of ten prepared questions.\nMr. Okafor made tea.\nShe asked her first question: \"What was the most important event of your life?\"\nHe considered this for a moment.\n\"Do you want the important event, or the one that changed me the most?\"\n\"Are they different?\"\n\"Almost always.\"\nShe crossed out her question and wrote a new one.\nFor the next two hours, he talked and she wrote as fast as she could.\nHe had emigrated from Nigeria at twenty-four with thirty dollars and a suitcase.\nHe had driven a night bus for six years before getting into university.\nHe had lost a son at thirty-nine, which he described in one sentence and did not return to.\nHe had learned to garden from a neighbor whose name he still remembered, though she had died in 1997.\nBy the time Zara left, her notebook was full and she had not asked eight of her ten prepared questions.\nShe spent four days writing the piece.\nWhen her teacher read it, she said it was the best thing Zara had written.\nZara didn't think it was her best writing.\nShe thought it was Mr. Okafor's best talking.\nWhich was better.", wordCount: 255 },
    { title: 'The Commission', content: "Fourteen-year-old Felix had been drawing since he was old enough to hold a pencil.\nHe drew on everything — sketchbooks, margins of homework, the back of receipts.\nThis summer, he got his first real commission.\nA neighbor who ran a small restaurant asked if Felix would paint a mural on the back wall of the dining room.\n\"Something that feels like this neighborhood,\" she said. \"Something that makes people feel at home.\"\nShe offered him a hundred and twenty dollars.\nFelix said yes without hesitating.\nThen he went home and panicked.\nA canvas you could throw away. A wall was permanent.\nHe spent two weeks doing nothing but sketches.\nThen one afternoon he walked the neighborhood for three hours, photographing things: the old tiled steps outside number twelve, the flower boxes on Mira's balcony, the way the afternoon light hit the fire escape on the building at the end of the block.\nHe went back to his room and drew from his photographs until two in the morning.\nThe mural took him nine days.\nOn the last day, the restaurant owner came to see it.\nShe stood very still for a long time.\n\"That's my neighborhood,\" she said finally.\nFelix looked at what he'd painted.\nHe hadn't painted anything grand or dramatic.\nJust the small, particular beauty of one street in one city at one time.\nIt felt more honest than anything he'd done before.\nHe shook her hand and walked home slowly, already thinking about what he would draw next.", wordCount: 248 },
    { title: 'The Distance Between', content: "My sister and I grew up in the same house, shared the same room until I was eleven, ate at the same table every night for fifteen years — and yet by the time she left for university, I felt like I was losing someone I was only just beginning to know.\nShe is three years older than me. When you are young, three years is enormous. She was in a different school, a different group of friends, a different world entirely.\nI remember being nine and watching her leave a party I wasn't allowed to attend. The door closing behind her felt like a sentence.\nBut the summer before she left, something changed.\nWe started watching the same television series and ended up on the sofa at the same time, just watching together.\nWe began talking about it, then about other things.\nI found out she was more uncertain than I thought. She found out I was angrier than I showed.\nThe night before she left, we stayed up until three in the morning, just talking.\nI don't remember most of what we said.\nBut I remember thinking: this is my sister. This is actually my sister.\nAt the airport the next morning, I didn't cry until I was back in the car.\nNow she calls on Sundays. Sometimes for five minutes. Sometimes two hours.\nI'm fourteen, and I look forward to Sunday more than any other day.\nThree years used to feel like a wall.\nNow it just feels like a gap we both decided to cross.", wordCount: 262 },
    { title: 'The Understudy', content: "For three years, Julia had been the understudy.\nShe had learned every line of every show the school drama club had performed — Midsummer Night's Dream, Our Town, The Importance of Being Earnest — and had stood in the wings at every performance watching someone else walk through her work.\nShe was never bitter about it. That was the strange part.\nShe just wanted to get the lines right.\nThis year, the lead in the spring production was a girl named Priya, who was genuinely brilliant and also had a habit of getting sick at the wrong moment.\nTwo hours before opening night, Priya called. Voice gone. Doctor's orders.\nThe director came to Julia in the hallway.\n\"You know the part.\"\n\"I know the part.\"\n\"All of it?\"\n\"All of it.\"\nShe changed into costume alone in a small room near the stage.\nShe thought about how many times she had stood in the wings watching.\nShe thought about the pause before the final monologue, which Priya always did one way.\nShe decided to do it her own way.\nWalking onto the stage, she felt — nothing dramatic. No terror, no exhilaration.\nJust the particular, focused calm of someone who has prepared for a long time.\nShe played the part through to the end.\nWhen she took her bow, the applause was long.\nAfterward, the drama teacher found her backstage.\n\"Three years,\" he said. \"Worth the wait?\"\nJulia considered the question seriously.\n\"Ask me in three more years,\" she said.", wordCount: 258 },
    { title: 'The Storm Season', content: "In the town where Eliza grew up, the storms came every autumn without fail.\nNot mild rain — serious storms that knocked out power, brought branches down across the road, and turned the creek at the edge of town into something fast and dangerous.\nEliza's family had a tradition: when the first serious storm of the season hit, everyone ate dinner by candlelight and someone told a story.\nNot a made-up story. A true one. Something that had actually happened.\nWhen Eliza was small, it was always her parents or her grandmother who told them.\nBut now she was thirteen, and this year her mother said, \"It's your turn.\"\nEliza thought for a long time about what to tell.\nShe could have told about the time she got lost hiking. Or the time she'd defended a friend from a group of older kids.\nInstead, she told a small story.\nA story about a Sunday last March when she had woken up very sad for no reason she could name.\nAbout how she had sat on the kitchen floor and eaten cereal and watched the garden for a long time.\nAbout how, gradually, the light changed, and the garden looked different, and something in her chest unknotted.\nAbout how she had not told anyone about this, but had thought about it many times since.\nWhen she finished, the candles were burning low.\nHer father didn't say anything.\nHer mother reached over and squeezed her hand once.\nThe storm rattled the windows.\nEliza felt, for a moment, completely understood.", wordCount: 255 },
    { title: 'The Revision', content: "In September, Ms. Adler assigned the class an essay: write about a moment that changed you.\nMarcus wrote his in forty-five minutes and handed it in confident it was good.\nIt was about the day his team won the regional basketball championship.\nMs. Adler handed it back the following week with a single comment: \"This is a moment that happened to you. What changed inside you?\"\nMarcus read this three times.\nHe rewrote the essay.\nThis time he wrote about the night before the championship, sitting in the parking lot with his friend DeShawn, both of them too nervous to go inside.\nAbout how DeShawn had said, quietly, that he didn't think he deserved to be on the team.\nAnd how Marcus had said, without thinking, \"That's because you're always comparing yourself to who you were yesterday. Stop that.\"\nAbout how he didn't understand why he'd said it until he was in the middle of saying it.\nAbout how he still thought about it.\nHe handed in the new version.\nMs. Adler's comment this time was three words: \"Now I see you.\"\nMarcus folded the essay and put it in his desk drawer at home.\nHe had written hundreds of things in his life.\nMost of them he forgot immediately.\nThis one he remembered precisely, sentence by sentence, for years.\nNot because it was brilliant.\nBecause it was true.\nAnd because it was the first time he understood that honesty in writing was not about saying everything.\nIt was about saying the right thing exactly right.", wordCount: 258 },
    { title: 'The Bridge Between Towns', content: "The two towns had a bridge between them — a concrete thing, nothing beautiful about it, built in the 1970s and wide enough for two lanes of traffic and a narrow walkway.\nFor most people it was just a crossing point.\nBut for Nia, who was twelve and lived on one side, and Sam, who was twelve and lived on the other, the bridge had become a meeting place.\nThey had met by accident — both leaning over the railing on the same Tuesday afternoon, watching the water below.\nNeither of them had spoken first. They just looked at the water together for a while.\nThen Sam had said, \"There's a fish under the shadow of that second pillar.\"\nNia had looked. There was.\nThey met there the following Tuesday without arranging it. And the Tuesday after that.\nSlowly, they started talking — about school, which they both found mostly bearable; about their families, which were very different; about the things they noticed that other people didn't.\nNeither of them told their families about the bridge meetings.\nNot because they were hiding something.\nBut because it felt important to have a thing that was just theirs.\nOne afternoon in October, Sam brought two hot chocolates in a thermos. Nia brought a bag of almonds.\nThey stood on the bridge and watched the river turn grey under the autumn sky.\n\"Same time next week?\" Sam asked.\n\"Same time,\" said Nia.\nThe fish was still under the second pillar.\nMaybe it had always been there.", wordCount: 262 },
    { title: 'Small Hours', content: "It started because Mara couldn't sleep.\nShe was fourteen and had been lying awake most nights for six months — not with worry, exactly, just with a mind that wouldn't stop.\nOn one of those nights she found her father at the kitchen table at two in the morning, with a cup of tea and a book.\nHe looked up. He didn't say anything about the time.\nHe just got up and made her a cup of tea as well.\nMara sat down.\nFor a while they didn't speak. The house was very quiet and the street outside was very quiet and the only sound was the ticking of the kitchen clock.\n\"Do you do this often?\" Mara asked.\n\"A few times a week,\" her father said.\n\"Does it help?\"\n\"I get some of my best thinking done at two in the morning. The day doesn't interrupt.\"\nMara looked at her tea.\n\"I think I've been afraid of being awake,\" she said. \"Like something is wrong with me.\"\n\"There's nothing wrong with having a mind that runs late,\" her father said.\nSomething in Mara relaxed.\nThey talked for an hour — about what she wanted, about what she was afraid she wouldn't become.\nHer father talked too, more than he usually did.\nSome of what he said surprised her.\nShe realized she had not really known him before this.\nAfter that, when she couldn't sleep, she went downstairs.\nHer father was usually there.\nSometimes they talked. Sometimes they just sat.\nBoth were enough.", wordCount: 250 },
  ],
}

exports.main = async (event) => {
  const { level } = event
  const levels = level ? [level] : Object.keys(STORIES).map(Number)

  const all = []
  for (const lv of levels) {
    for (const s of (STORIES[lv] || [])) {
      all.push({ ...s, level: lv, status: 'published', readCount: 0, coverImage: '', audioUrl: '', createdAt: Date.now() })
    }
  }

  let inserted = 0
  for (let i = 0; i < all.length; i += 5) {
    const batch = all.slice(i, i + 5)
    const results = await Promise.all(
      batch.map(data => db.collection('stories').add({ data }).then(() => true).catch(() => false))
    )
    inserted += results.filter(Boolean).length
  }

  return { total: all.length, inserted }
}
